services:
  php-server:
    image: php:8.2-cli
    container_name: php-server
    working_dir: /var/www/html
    volumes:
      
      - ./src/php:/var/www/html

    ports:
      - "3000:8000"
    command: php -S 0.0.0.0:8000